package main

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
)

var input = []byte(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)

func TestPart1(t *testing.T) {
	output := part1(bytes.Split(input, []byte("\n")))
	assert.Equal(t, 21, output)
}

func TestPart2(t *testing.T) {
	output := part2(bytes.Split(input, []byte("\n")))
	assert.Equal(t, 40, output)
}
